# Generated by Django 5.2.11 on 2026-02-23 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_bonafide_approval_chain"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bonafiderequest",
            old_name="dean_at",
            new_name="dean_approved_at",
        ),
        migrations.RenameField(
            model_name="bonafiderequest",
            old_name="hod_at",
            new_name="hod_approved_at",
        ),
        migrations.RenameField(
            model_name="bonafiderequest",
            old_name="tutor_at",
            new_name="tutor_approved_at",
        ),
        migrations.RemoveField(
            model_name="bonafiderequest",
            name="current_stage",
        ),
        migrations.RemoveField(
            model_name="bonafiderequest",
            name="dean_name",
        ),
        migrations.RemoveField(
            model_name="bonafiderequest",
            name="dean_status",
        ),
        migrations.RemoveField(
            model_name="bonafiderequest",
            name="hod_name",
        ),
        migrations.RemoveField(
            model_name="bonafiderequest",
            name="hod_status",
        ),
        migrations.RemoveField(
            model_name="bonafiderequest",
            name="purpose",
        ),
        migrations.RemoveField(
            model_name="bonafiderequest",
            name="tutor_name",
        ),
        migrations.RemoveField(
            model_name="bonafiderequest",
            name="tutor_status",
        ),
        migrations.AddField(
            model_name="bonafiderequest",
            name="ai_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bonafiderequest",
            name="ai_model_used",
            field=models.CharField(
                choices=[("gemini", "Google Gemini"), ("groq", "Groq Llama")],
                default="gemini",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bonafiderequest",
            name="current_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bonafiderequest",
            name="dean_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dean_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bonafiderequest",
            name="final_rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="bonafiderequest",
            name="hod_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hod_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bonafiderequest",
            name="tutor_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutor_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bonafiderequest",
            name="checklist",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="bonafiderequest",
            name="contact",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="bonafiderequest",
            name="extracted",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="bonafiderequest",
            name="permission_file",
            field=models.FileField(upload_to="bonafide_permissions/"),
        ),
        migrations.AlterField(
            model_name="bonafiderequest",
            name="reason",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="bonafiderequest",
            name="roll_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="bonafiderequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("tutor_review", "Under Tutor Review"),
                    ("tutor_approved", "Tutor Approved"),
                    ("tutor_rejected", "Tutor Rejected"),
                    ("hod_review", "Under HOD Review"),
                    ("hod_approved", "HOD Approved"),
                    ("hod_rejected", "HOD Rejected"),
                    ("dean_review", "Under Dean Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bonafiderequest",
            name="student_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="dean_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACADEMIC", "Academic"),
                    ("AUTONOMOUS", "Autonomous"),
                    ("ADMIN", "Administrative"),
                    ("PLACEMENT", "Placement"),
                    ("STUDENT_AFFAIRS", "Student Affairs"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="designation",
            field=models.CharField(
                choices=[
                    ("TUTOR", "Tutor"),
                    ("PROGRAM_COORDINATOR", "Program Coordinator"),
                    ("HOD", "Head of Department"),
                    ("DEAN", "Dean"),
                    ("PRINCIPAL", "Principal"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="student_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutors",
                to="accounts.studentclass",
            ),
        ),
        migrations.AlterField(
            model_name="studentclass",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="InternshipRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("roll_number", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=15)),
                ("company_name", models.CharField(max_length=200)),
                ("internship_type", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("parents_contact", models.CharField(max_length=15)),
                (
                    "permission_file",
                    models.FileField(upload_to="internship_permissions/"),
                ),
                ("offer_letter", models.FileField(upload_to="internship_offers/")),
                ("parent_consent", models.FileField(upload_to="internship_consents/")),
                (
                    "ai_model_used",
                    models.CharField(
                        choices=[("gemini", "Google Gemini"), ("groq", "Groq Llama")],
                        default="gemini",
                        max_length=20,
                    ),
                ),
                ("extracted", models.JSONField(blank=True, default=dict)),
                ("checklist", models.JSONField(blank=True, default=dict)),
                ("is_valid", models.BooleanField(default=False)),
                ("explanation", models.TextField(blank=True)),
                ("ai_confidence", models.FloatField(blank=True, null=True)),
                (
                    "offer_suspicious_indicators",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("tutor_review", "Under Tutor Review"),
                            ("tutor_approved", "Tutor Approved"),
                            ("tutor_rejected", "Tutor Rejected"),
                            ("hod_review", "Under HOD Review"),
                            ("hod_approved", "HOD Approved"),
                            ("hod_rejected", "HOD Rejected"),
                            ("dean_review", "Under Dean Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("tutor_approved_at", models.DateTimeField(blank=True, null=True)),
                ("tutor_comment", models.TextField(blank=True)),
                ("hod_approved_at", models.DateTimeField(blank=True, null=True)),
                ("hod_comment", models.TextField(blank=True)),
                ("dean_approved_at", models.DateTimeField(blank=True, null=True)),
                ("dean_comment", models.TextField(blank=True)),
                ("final_rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_internship_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dean_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internship_dean_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hod_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internship_hod_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internship_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tutor_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internship_tutor_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
