# Generated by Django 6.0 on 2026-02-05 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonafideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=255)),
                ('roll_number', models.CharField(blank=True, max_length=128)),
                ('contact', models.CharField(blank=True, max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('permission_file', models.FileField(blank=True, null=True, upload_to='bonafide_permissions/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonafide_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
