# Generated by Django 6.0 on 2026-02-05 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bonafiderequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='dean_type',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='hod_department',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='department',
        ),
        migrations.AddField(
            model_name='bonafiderequest',
            name='checklist',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonafiderequest',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bonafiderequest',
            name='extracted',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonafiderequest',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentclass'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentclass'),
        ),
    ]
