# Generated by Django 6.0 on 2026-02-05 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_staffprofile_dean_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='dean_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='designation',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='hod_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hods', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='accounts.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='accounts.studentclass'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.studentclass'),
        ),
        migrations.DeleteModel(
            name='BonafideRequest',
        ),
    ]
