# Generated by Django 6.0 on 2026-02-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_bonafiderequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='bonafiderequest',
            name='checklist',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonafiderequest',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bonafiderequest',
            name='extracted',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonafiderequest',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
