# Generated by Django 6.0 on 2026-02-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
