# Generated by Django 6.0.2 on 2026-02-19 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_mobile_number_customuser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonafiderequest',
            name='hod_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonafide_hod_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonafiderequest',
            name='pc_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonafide_pc_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonafiderequest',
            name='tutor_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonafide_tutor_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
