# Generated by Django 6.0.2 on 2026-02-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_bonafiderequest_hod_actor_bonafiderequest_pc_actor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonafiderequest',
            name='hod_actor',
        ),
        migrations.RemoveField(
            model_name='bonafiderequest',
            name='pc_actor',
        ),
        migrations.RemoveField(
            model_name='bonafiderequest',
            name='tutor_actor',
        ),
    ]
